Dz#3
dj-b00b/2022-2-VK-EDU-FS-Frontend-V-Cheverkalov pull request #4
Opened 2022-10-24 02:45 UTC by dj-b00b

# Домашнее задание №3

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
* сверстана страница с чатами в соответствии с выданным макетом, код компонентов максимально разнесен по отдельным файлам
* реализован переход с экрана списка чатов на экран чата, реализованный в прошлом ДЗ

2022-10-24 18:52 UTC, HaseProgram commented on simple-chat/src/chats/index.html
> +    </script>
Не нужно

2022-10-24 18:53 UTC, HaseProgram commented on simple-chat/src/chats/index.html
> +    <div class="block_chat" onclick="goToChat();">
goToChat здесь работать не будет, так как у нас вебпак собирает модулем. В JS файле надо сделать через ``addEventListener``

2022-10-24 18:55 UTC, HaseProgram requested changes
Необходимо
- [ ] Разобраться с конфликтами МР
- [ ] Заставить работать переходы из страницы чатов на страницу отдельного чата

2022-10-30 13:23 UTC, dj-b00b commented
Исправил все замечания! Просто у меня вышло так, что я их исправил и сделал сразу 4 ДЗ и создал пул-реквест на 4 ДЗ, но думаю, более правильней будет исправить замечания и в этом пул-реквесте

2022-11-01 16:47 UTC, HaseProgram approved these changes
Привет, зачтено, 12

2022-11-01 16:47 UTC, merged